name: 'DynamicLights'
description: 'Emit Light from Held Items using the 1.17 Light Blocks.'
author: 'xCykrix and alairack'
version: '${project.version}'

main: com.github.xcykrix.dynamiclights.DynamicLights
api-version: '1.20'
load: 'POSTWORLD'

depend:
    - 'ProtocolLib'

permissions:
    dynamiclights.lock:
        description: "Toggle placing light sources from your off hand."
        default: true
