name: 'DynamicLights'
description: 'Emit Light from Held Items using the 1.17 Light Blocks.'
website: 'https://www.spigotmc.org/resources/dynamiclights.110707/'
author: 'xCykrix'
version: '${project.version}'

main: com.github.xcykrix.dynamiclights.DynamicLights
api-version: '1.20'
load: 'POSTWORLD'

depend:
    - 'ProtocolLib'

permissions:
    dynamiclights.lock:
        description: "Toggle placing light sources from your off hand."
        default: true
